final-talk_group3.pdf: final-talk_group3.tex
	latexmk -pdf -pdflatex="pdflatex -shell-escape" final-talk_group3.tex

clean:
	rm -rf *.aux *.fdb_latexmk *.fls *.log *.nav *.out *.pdf *.snm *.toc _minted-final-talk_group3
