final-report_group3.pdf: final-report_group3.tex
	latexmk -pdf -pdflatex="pdflatex -shell-escape" final-report_group3.tex

clean:
	rm -rf *.aux *.fdb_latexmk *.fls *.log *.nav *.out *.pdf *.snm *.toc _minted-final-report_group3 final-report_group3.synctex.gz
